services:
  novatria-bot:
    build:
      context: .
    container_name: novatria-bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    init: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  novatria-clear-global:
    build:
      context: .
    env_file:
      - .env
    restart: "no"
    init: true
    command: npm run clear:global
    profiles:
      - tools
